CREATE TABLE `JokerArchive`.`PiggyBankCoinRecord` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `piggyBankId` CHAR(36) NOT NULL,
  `act` INT NOT NULL COMMENT '1:ResetPiggyBank, 2:CollectCoin, 3:BreakPiggyBank',
  `beforeCoin` INT NOT NULL,
  `incrCoin` INT NOT NULL,
  `gameId` VARCHAR(255) NOT NULL DEFAULT '',
  `game` VARCHAR(255) NOT NULL DEFAULT '',
  `mode` VARCHAR(255) NOT NULL DEFAULT '',
  `mCoin` INT NOT NULL DEFAULT '0',
  `bCoin` INT NOT NULL DEFAULT '0',
  `marble` INT NOT NULL DEFAULT '0',
  `bonus` INT NOT NULL DEFAULT '0',
  `cash` INT NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JokerArchive`.`CampaignPrizeRecord` (
  `campaignPrizeRecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `prizeType` INT UNSIGNED NOT NULL,
  `commonPrizes` MEDIUMTEXT NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`campaignPrizeRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JokerArchive`.`CampaignMissionRecord` (
  `campaignMissionRecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `missionId` INT NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`campaignMissionRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JokerArchive`.`UserPointRecord` (
  `userPointRecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `pointId` INT NOT NULL,
  `amount` INT NOT NULL,
  `beforePoint` INT NOT NULL,
  `type` INT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userPointRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JokerArchive`.`PointShopRecord` (
  `pointShopRecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `pointId` INT NOT NULL,
  `amount` INT NOT NULL,
  `purchaseOption` INT NOT NULL,
  `exchangeCount` INT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pointShopRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JokerArchive`.`NameChangedRecord` (
  `nameChangedRecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `oldName` VARCHAR(255) NOT NULL,
  `newName` VARCHAR(255) NOT NULL,
  `oldState` INT NOT NULL,
  `newState` INT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`nameChangedRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
